<?php
# This file pretends to be a /robots.txt file (via Apache rewrite, see configs/.htaccess)

ini_set( 'display_errors', 0 );
error_reporting( 0 );

header( 'Content-Type: text/plain' );

echo "# The following lines are generated by robots.php\n";

$robotsDisallowed = getenv( 'ROBOTS_DISALLOWED' );
if ( !empty( $robotsDisallowed ) && in_array( strtolower($robotsDisallowed), [ 'true', '1' ] ) ) {
	die( "User-agent: *\nDisallow: /\n" );
}

// Advertise the combined sitemap index (served by sitemap.php) when any
// wiki on this host has sitemap files
require_once __DIR__ . '/canasta-sitemaps.php';
$serverName = $_SERVER['HTTP_HOST'] ?? 'localhost';
$scheme = parse_url( getenv( 'MW_SITE_SERVER' ) ?: 'https://localhost', PHP_URL_SCHEME ) ?: 'https';
if ( canastaHostSitemapIndexes( $serverName ) ) {
	echo "Sitemap: $scheme://$serverName/sitemap.xml\n";
}

readfile( 'robots-main.txt' );

// If the file `extra-robots.txt` is created under the name
// `/var/www/mediawiki/extra-robots.txt` then its contents get appended to the
// default `robots.txt`
if ( is_readable( 'extra-robots.txt' ) ) {
	// Extra line to separate the files so that rules don't combine
	echo "\n";
	readfile( 'extra-robots.txt' );
}
